# Generated by Django 5.0.7 on 2024-08-05 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuredPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('age', models.IntegerField(verbose_name='Věk')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefonní číslo')),
            ],
            options={
                'verbose_name': 'Pojištěná osoba',
                'verbose_name_plural': 'Pojištěné osoby',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(max_length=100, verbose_name='Typ pojištění')),
                ('coverage_amount', models.FloatField(verbose_name='Výše krytí')),
                ('premium', models.FloatField(verbose_name='Pojistné')),
                ('start_date', models.DateField(verbose_name='Datum začátku pojištění')),
                ('end_date', models.DateField(verbose_name='Datum konce pojištění')),
                ('insured_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance.insuredperson', verbose_name='Pojištěná osoba')),
            ],
            options={
                'verbose_name': 'Pojistka',
                'verbose_name_plural': 'Pojistky',
            },
        ),
    ]
