# Generated by Django 5.0.7 on 2024-08-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_insuredperson_address_insuredperson_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredperson',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='Telefonní číslo'),
        ),
    ]
