# Generated by Django 5.0.7 on 2024-08-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_alter_insuredperson_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuredperson',
            name='address',
        ),
        migrations.RemoveField(
            model_name='insuredperson',
            name='age',
        ),
        migrations.AddField(
            model_name='insuredperson',
            name='city',
            field=models.CharField(default='Neznámé město', max_length=100, verbose_name='Město'),
        ),
        migrations.AddField(
            model_name='insuredperson',
            name='postal_code',
            field=models.CharField(default='00000', max_length=10, verbose_name='PSČ'),
        ),
        migrations.AddField(
            model_name='insuredperson',
            name='street_address',
            field=models.CharField(default='Neznámá ulice', max_length=255, verbose_name='Ulice a číslo popisné'),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
