# Generated by Django 5.0.7 on 2024-08-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_remove_insuredperson_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredperson',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254, verbose_name='Email'),
        ),
    ]
