# Generated by Django 5.0.7 on 2024-08-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_alter_insuredperson_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredperson',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='street_address',
            field=models.CharField(max_length=255, verbose_name='Ulice a číslo popisné'),
        ),
    ]
