# Generated by Django 5.0.7 on 2024-08-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_alter_insuredperson_city_alter_insuredperson_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název pojištění')),
                ('description', models.TextField(verbose_name='Popis pojištění')),
                ('coverage_amount', models.FloatField(verbose_name='Výše krytí')),
                ('premium', models.FloatField(verbose_name='Pojistné')),
            ],
            options={
                'verbose_name': 'Typ pojištění',
                'verbose_name_plural': 'Typy pojištění',
            },
        ),
    ]
