# Generated by Django 5.0.7 on 2024-08-23 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_insurancetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancetype',
            name='coverage_amount',
        ),
        migrations.RemoveField(
            model_name='insurancetype',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_type',
        ),
        migrations.AlterField(
            model_name='insurancetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Popis typu pojištění'),
        ),
        migrations.AlterField(
            model_name='insurancetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název typu pojištění'),
        ),
        migrations.CreateModel(
            name='InsuranceSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název podtypu pojištění')),
                ('description', models.TextField(blank=True, verbose_name='Popis podtypu pojištění')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='insurance.insurancetype', verbose_name='Typ pojištění')),
            ],
            options={
                'verbose_name': 'Podtyp pojištění',
                'verbose_name_plural': 'Podtypy pojištění',
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='insurance_subtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insurance.insurancesubtype', verbose_name='Podtyp pojištění'),
        ),
    ]
