# Generated by Django 5.0.7 on 2024-08-25 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_remove_policy_coverage_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='insurance_subtype',
        ),
        migrations.AlterField(
            model_name='policy',
            name='premium',
            field=models.FloatField(editable=False, verbose_name='Pojistné'),
        ),
        migrations.CreateModel(
            name='InsuranceCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název pojistného krytí')),
                ('description', models.TextField(blank=True, verbose_name='Popis pojistného krytí')),
                ('premium', models.FloatField(default=0.0, verbose_name='Pojistné')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='insurance.insurancetype', verbose_name='Typ pojištění')),
            ],
            options={
                'verbose_name': 'Pojistné krytí',
                'verbose_name_plural': 'Pojistná krytí',
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='insurance_coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.insurancecoverage', verbose_name='Pojistné krytí'),
        ),
        migrations.DeleteModel(
            name='InsuranceSubType',
        ),
    ]
