# Generated by Django 5.0.7 on 2024-08-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_remove_policy_insurance_subtype_alter_policy_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredperson',
            name='id_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Rodné číslo'),
        ),
    ]
