# Generated by Django 5.0.7 on 2024-09-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0017_alter_insuredperson_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredperson',
            name='first_name',
            field=models.CharField(max_length=10, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='last_name',
            field=models.CharField(max_length=10, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='postal_code',
            field=models.CharField(max_length=6, verbose_name='PSČ'),
        ),
    ]
