# Generated by Django 5.0.7 on 2024-09-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0018_alter_insuredperson_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredperson',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='street_address',
            field=models.CharField(max_length=30, verbose_name='Ulice a číslo popisné'),
        ),
    ]
