# Generated by Django 5.0.7 on 2024-09-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0019_alter_insuredperson_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredperson',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
