# Generated by Django 5.0.7 on 2024-09-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0020_alter_insuredperson_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredperson',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='id_number',
            field=models.CharField(max_length=11, verbose_name='Rodné číslo'),
        ),
    ]
